#!/bin/bash
echo Building...
./gradlew build -q

count=$1

function clean_up {
	if [[ count -eq 2 ]]; then
		kill -9 $pid1
		kill -9 $pid2
	else
                kill -9 $pid1
                kill -9 $pid2
		kill -9 $pid3
		kill -9 $pid4
	fi
}


if [[ count -eq 2 ]]; then
        echo Starting two Servers
	xterm -e java -cp build/libs/Quoridor-1.0.jar server.EchoServer --port 7070 &
	pid1=$!
	xterm -e java -cp build/libs/Quoridor-1.0.jar server.EchoServer --port 7171 &
        pid2=$! 
	sleep 1	
	echo Starting Client
	xterm -e java -cp build/libs/Quoridor-1.0.jar client.CMT localhost:7070 localhost:7171 --delay 1000

else
        echo Starting four Servers
        xterm -e java -cp build/libs/Quoridor-1.0.jar server.EchoServer --port 7070 &
        pid1=$!

        xterm -e java -cp build/libs/Quoridor-1.0.jar server.EchoServer --port 7171 &
        pid2=$!

        xterm -e java -cp build/libs/Quoridor-1.0.jar server.EchoServer --port 7272 &
        pid3=$!

        xterm -e java -cp build/libs/Quoridor-1.0.jar server.EchoServer --port 7373 &
        pid4=$! 
	sleep 1
        echo Starting Client
        xterm -e java -cp build/libs/Quoridor-1.0.jar client.CMT localhost:7070 localhost:7171 localhost:7272 localhost:7373 --delay 1000

fi

clean_up
exit 0
